import { lazyRetry } from '@/utils/lazyRetry';

export const LoginPage = lazyRetry(() => import('@/pages/LoginPage'));
export const DashboardPage = lazyRetry(() => import('@/pages/DashboardPage'));
export const TasksPage = lazyRetry(() => import('@/pages/TasksPage'));
export const ReportsPage = lazyRetry(() => import('@/pages/ReportsPage'));
export const MeetingsPage = lazyRetry(() => import('@/pages/MeetingsPage'));
export const ChatPage = lazyRetry(() => import('@/pages/ChatPage'));
export const AdminPage = lazyRetry(() => import('@/pages/AdminPage'));
export const TeamPage = lazyRetry(() => import('@/pages/TeamPage'));
export const SalesPage = lazyRetry(() => import('@/pages/SalesPage'));
export const NotFoundPage = lazyRetry(() => import('@/pages/NotFoundPage'));
export const ProfilePage = lazyRetry(() => import('@/pages/ProfilePage'));
export const TeamInsightsPage = lazyRetry(() => import('@/pages/TeamInsightsPage'));
export const ProjectsPage = lazyRetry(() => import('@/pages/projects/ProjectsPage'));
export const ProjectDetailsPage = lazyRetry(() => import('@/pages/projects/ProjectDetailsPage'));
export const KanbanBoardPage = lazyRetry(() => import('@/pages/projects/KanbanBoardPage'));
export const AttendancePage = lazyRetry(() => import('@/pages/AttendancePage'));
export const AttendanceActivityPage = lazyRetry(() => import('@/pages/AttendanceActivityPage'));
export const MemberProgressPage = lazyRetry(() => import('@/pages/MemberProgressPage'));
export const MemberKpiDetailPage = lazyRetry(() => import('@/pages/MemberKpiDetailPage'));
export const LeadDetailsPage = lazyRetry(() => import('@/pages/leads/LeadDetailsPage'));
export const BulkAddLeadsPage = lazyRetry(() => import('@/pages/BulkAddLeadsPage'));
